#!/bin/bash

CFG_FILE='fbdev_config.sh'
while getopts ":c:" opt; do
    case $opt in
        c)
            CFG_FILE=$OPTARG
            ;;
        *)
            echo "* $OPTARG"
            ;;
    esac
done

shift $((OPTIND - 1))

CMD=$1
ARGV=$@

if [ -f ./$CFG_FILE ]; then
    . ./$CFG_FILE
else
    echo "ERROR: No fbdev_config.sh file found!"
    echo "Please create your own config from template file fbdev_config.sh.template"
    exit 1
fi

cd $FHIRBASE_HOME;
export FHIRBASE_HOME;

function help_cmd {
    cat <<EOF
Usage: $0 [command] [args]

Available commands:

-h || help                this help text
test [test1, test2, ...]  run tests from dev/test dir. if test names are provided, run specified tests
install dbname            generate and install fhirbase schema into specified DB
build                     build fhirbase.sql file
EOF
}

function install_cmd {
    if [ -z "$1" ]; then
        echo "install command requires dbname argument"
        exit 1
    else
        echo "Installing fhirbase into DB $1..."
        psql $PSQL_ARGS -d $1 < install.sql
    fi
}

function recreate_db {
    echo "DROP DATABASE $1; CREATE DATABASE $1;" | psql $PSQL_ARGS -d postgres;
}

function test_cmd {
    echo "Running fhirbase tests..."

    glob=''

    for word in $ARGV; do
        if [ "$word" != "test" ]; then
            glob="$glob $FHIRBASE_HOME/test/${word}_test.sql"
        fi
    done

    if [ "$glob" = "" ]; then glob="$FHIRBASE_HOME/test/*_test.sql"; fi

    export TEST_DB_NAME
    recreate_db $TEST_DB_NAME
    cd $FHIRBASE_HOME/test &&
    $FHIRBASE_HOME/pg_prove $PSQL_ARGS -d $TEST_DB_NAME $glob

    exit $? # return test subprocess exit code
}

case "$CMD" in
    "test" )
        test_cmd
        ;;
    "install" )
        install_cmd $2
        ;;
    "build" )
        echo "Building fhirbase.sql"

        recreate_db $BUILD_DB_NAME
        install_cmd $BUILD_DB_NAME

        pg_dump $PSQL_ARGS \
                --format=plain \
                --schema=fhir \
                --no-owner \
                --file=$FHIRBASE_HOME/../fhirbase.sql \
                $BUILD_DB_NAME && echo "FhirBase schema successfully dumped to $FHIRBASE_HOME/../fhirbase.sql"

        cd $FHIRBASE_HOME/.. && psql $PSQL_ARGS -d $BUILD_DB_NAME < fhirbase_test.sql

        exit $? # return tests exit status
        ;;
    *)
        help_cmd
        exit
esac

exit 0
