#!/bin/bash

if [ -f ./fbdev_config.sh ]; then
    . ./fbdev_config.sh
else
    echo "ERROR: No fbdev_config.sh file found!"
    echo "Please create your own config from template file fbdev_config.sh.template"
    exit 1
fi

cd $FHIRBASE_HOME;
export FHIRBASE_HOME;

function help_cmd {
    cat <<EOF
Usage: $0 [command] [args]

Available commands:

-h || help             this help text
test                   run tests from dev/test dir
install dbname         generate and install fhirbase schema into specified DB
build                  build fhirbase.sql file
EOF
}

function compile_js {
    coffee --compile --output $FHIRBASE_HOME/js $FHIRBASE_HOME/js_src
}

function install_cmd {
    if [ -z "$1" ]; then
        echo "install command requires dbname argument"
        exit 1
    else
        compile_js
        psql $PSQL_ARGS -d $1 < install.sql
    fi
}

function recreate_db {
    echo "DROP DATABASE $1; CREATE DATABASE $1;" | psql $PSQL_ARGS -d postgres;
}

function test_cmd {
    compile_js
    recreate_db $TEST_DB_NAME
    cd $FHIRBASE_HOME/test && $FHIRBASE_HOME/pg_prove $PSQL_ARGS -d $TEST_DB_NAME $FHIRBASE_HOME/test/*_test.sql
}

case "$1" in
    "test" )
        test_cmd
        ;;
    "install" )
        install_cmd $2
        ;;
    "build" )
        recreate_db $BUILD_DB_NAME
        install_cmd $BUILD_DB_NAME

        pg_dump $PSQL_ARGS \
          --format=plain \
          --schema=fhir $BUILD_DB_NAME \
          --no-owner > $FHIRBASE_HOME/../fhirbase.sql &&
          echo "FhirBase schema successfully dumped to $FHIRBASE_HOME/../fhirbase.sql"
        ;;
    *)
        help_cmd
        exit
esac

exit 0
