// Generated by CoffeeScript 1.6.3
(function() {
  this.log = function(mess) {
    return plv8.elog(NOTICE, JSON.stringify(mess));
  };

  this.column_name = function(name, type) {
    return name.replace('[x]', "_" + type);
  };

  this.underscore = function(str) {
    return str.replace(/([a-z\d])([A-Z]+)/g, "$1_$2").replace(/[-\s]+/g, "_").replace('.', '').toLowerCase();
  };

  this.table_name = function(path) {
    return underscore(path.join('_'));
  };

  this.short_table_name = function(path) {
    var first, hvost, len, num_from_end;
    first = path[0];
    num_from_end = path.len - Math.min(path.length - 1, 2);
    len = path.length;
    hvost = path.slice(num_from_end, len);
    return underscore(([path[0]].concat(hvost)).join('__'));
  };

}).call(this);
